# basic setting
title: vivo互联网技术 
author: vivo 
#email: 2020labs@vivo.com 
description: > # this means to ignore newlines until "baseurl:" 
  tech.vivo.com 

# build setting 
theme: jekyll-theme-cayman
